spring.datasource:
  url: jdbc:h2:./camunda-h2-default/process-engine;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
  username: camunda
  password: camunda
  driver-class-name: org.h2.Driver

camunda:
  bpm:
    job-execution:
      core-pool-size: 10
    authorization.enabled: true

server:
  port: 8081
